site_dir: docs
site_name: Prompt Versioner
site_description: Comprehensive Python library for managing and versioning LLM prompts
site_author: Sveva Pepe
site_url: https://pepes97.github.io/prompt-versioner/

repo_name: pepes97/prompt-versioner
repo_url: https://github.com/pepes97/prompt-versioner
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Sveva Pepe

theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  icon:
    logo: material/code-braces
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: pepes97
      repo: prompt-versioner
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pepes97/prompt-versioner
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/prompt-versioner/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Core Concepts: user-guide/core-concepts.md
    - Version Management: user-guide/version-management.md
    - Metrics & Tracking: user-guide/metrics-tracking.md
    - A/B Testing: user-guide/ab-testing.md
    - Performance Monitoring: user-guide/performance-monitoring.md
    - Web Dashboard: user-guide/web-dashboard.md
    - Collaboration: user-guide/collaboration.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Workflows: examples/advanced-workflows.md
    - Integration Examples: examples/integrations.md
    - Best Practices: examples/best-practices.md
  - API Reference:
    - Core:
      - Versioner: api-reference/core/versioner.md
      - Version Manager: api-reference/core/version-manager.md
      - Enums: api-reference/core/enums.md
    - CLI:
      - Commands: api-reference/cli/commands.md
      - Utils: api-reference/cli/utils.md
    - Storage:
      - Database: api-reference/storage/database.md
      - Queries: api-reference/storage/queries.md
      - Schema: api-reference/storage/schema.md
    - Metrics:
      - Tracker: api-reference/metrics/tracker.md
      - Analyzer: api-reference/metrics/analyzer.md
      - Calculator: api-reference/metrics/calculator.md
      - Models: api-reference/metrics/models.md
    - Testing:
      - A/B Test: api-reference/testing/ab-test.md
      - Runner: api-reference/testing/runner.md
    - Web:
      - Flask Builder: api-reference/web/flask-builder.md
      - Controllers: api-reference/web/controllers.md
