site_name: Prompt Versioner
site_url: https://pepes97.github.io/prompt-versioner/
site_description: A comprehensive Python library for managing and versioning LLM prompts
site_author: Sveva Pepe
repo_url: https://github.com/pepes97/prompt-versioner
repo_name: pepes97/prompt-versioner
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
  - User Guide:
    - Basic Usage: guide/basic-usage.md
    - Version Management: guide/version-management.md
    - Metrics Tracking: guide/metrics-tracking.md
    - A/B Testing: guide/ab-testing.md
    - Performance Monitoring: guide/performance-monitoring.md
  - Web Dashboard:
    - Overview: dashboard/overview.md
    - Features: dashboard/features.md
    - Themes: dashboard/themes.md
  - CLI Reference:
    - Commands: cli/commands.md
    - Examples: cli/examples.md
  - API Reference:
    - Core: api/core.md
    - Testing: api/testing.md
    - Metrics: api/metrics.md
    - Storage: api/storage.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Advanced Examples: examples/advanced.md
    - Production Examples: examples/production.md
  - Contributing: contributing.md
  - Changelog: changelog.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pepes97/prompt-versioner
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/prompt-versioner/
  version:
    provider: mike
