name: Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry install --no-root --no-interaction

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: poetry publish -r testpypi --no-interaction
